/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-23 17:46:09 UTC)
 * on 2013-05-31 at 13:56:53 UTC 
 * Modify at your own risk.
 */

package net.gogo.server.onii.api.tictachead.model;

/**
 * Model definition for Room.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Room extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean finished;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gameState;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer gameType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxPlayer;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long owner;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long playerTurn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> players;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long roomID;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getFinished() {
    return finished;
  }

  /**
   * @param finished finished or {@code null} for none
   */
  public Room setFinished(java.lang.Boolean finished) {
    this.finished = finished;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGameState() {
    return gameState;
  }

  /**
   * @param gameState gameState or {@code null} for none
   */
  public Room setGameState(java.lang.String gameState) {
    this.gameState = gameState;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getGameType() {
    return gameType;
  }

  /**
   * @param gameType gameType or {@code null} for none
   */
  public Room setGameType(java.lang.Integer gameType) {
    this.gameType = gameType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxPlayer() {
    return maxPlayer;
  }

  /**
   * @param maxPlayer maxPlayer or {@code null} for none
   */
  public Room setMaxPlayer(java.lang.Integer maxPlayer) {
    this.maxPlayer = maxPlayer;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getOwner() {
    return owner;
  }

  /**
   * @param owner owner or {@code null} for none
   */
  public Room setOwner(java.lang.Long owner) {
    this.owner = owner;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPlayerTurn() {
    return playerTurn;
  }

  /**
   * @param playerTurn playerTurn or {@code null} for none
   */
  public Room setPlayerTurn(java.lang.Long playerTurn) {
    this.playerTurn = playerTurn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getPlayers() {
    return players;
  }

  /**
   * @param players players or {@code null} for none
   */
  public Room setPlayers(java.util.List<java.lang.Long> players) {
    this.players = players;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getRoomID() {
    return roomID;
  }

  /**
   * @param roomID roomID or {@code null} for none
   */
  public Room setRoomID(java.lang.Long roomID) {
    this.roomID = roomID;
    return this;
  }

  @Override
  public Room set(String fieldName, Object value) {
    return (Room) super.set(fieldName, value);
  }

  @Override
  public Room clone() {
    return (Room) super.clone();
  }

}
